[env]
  TERM = "alacritty"

[scrolling]
  history = 50000

[cursor]
  style.shape = "Block"
  style.blinking = "Off"

[keyboard]
  bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left",  mods = "Alt", chars = "\u001BB" },
  ]

[window]
  dynamic_title = true
  padding.x = 9
  padding.y = 12
  decorations = "buttonless"

[font]
  size = 16
  normal.family = "MesloLGS Nerd Font Mono"

[colors.primary]
  background = '#282a36'
  foreground = '#eff0eb'

[colors.cursor]
  cursor = '#97979b'

[colors.selection]
  text = '#282a36'
  background = '#feffff'

[colors.normal]
  black = '#282a36'
  red = '#ff5c57'
  green = '#5af78e'
  yellow = '#f3f99d'
  blue = '#57c7ff'
  magenta = '#ff6ac1'
  cyan = '#9aedfe'
  white = '#f1f1f0'

[colors.bright]
  black = '#686868'
  red = '#ff5c57'
  green = '#5af78e'
  yellow = '#f3f99d'
  blue = '#57c7ff'
  magenta = '#ff6ac1'
  cyan = '#9aedfe'
  white = '#eff0eb'
